version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    hostname: '${RABBITMQ_HOSTNAME}'
    environment:
      RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER}'
      RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS}'
    ports:
      - "15672:15672"
      - "5672:5672"

  converter-worker:
    build: './converter-worker'
    user: root
    volumes:
      - ./Files:/app/Files
    env_file:
      - .env
    depends_on:
      - rabbitmq
